### ISSUE TITLE
SMTP Timeout Error

### ISSUE THREAD

**Issue by bcardi** [bcardi/fixedit#1]
**Rails application. Trying to send an email confirmation with devise. My ActionMailer settings are as follows**

```
  ActionMailer::Base.smtp_settings = {
    :address        => ENV['SMTP_HOST'],
    :port           => ENV['SMTP_PORT'],
    :authentication => :plain,
    :user_name      => ENV['SMTP_USER'],
    :password       => ENV['SMTP_PASSWORD'],
    :domain         => 'localhost:3000',
    :enable_starttls_auto => true
  }
```

**Where SMTP_PORT = 465**

**When I try to send an email, I get the following error**

```
C:\Ruby193\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Ruby193/bin/rake --trace db:seed[--trace]
** Invoke db:seed (first_time)
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
** Execute db:seed
rake aborted!
Timeout::Error
C:/Ruby193/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill'
C:/Ruby193/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
C:/Ruby193/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
C:/Ruby193/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
C:/Ruby193/lib/ruby/1.9.1/net/smtp.rb:929:in `recv_response'
C:/Ruby193/lib/ruby/1.9.1/net/smtp.rb:552:in `block in do_start'
C:/Ruby193/lib/ruby/1.9.1/net/smtp.rb:939:in `critical'
C:/Ruby193/lib/ruby/1.9.1/net/smtp.rb:552:in `do_start'
C:/Ruby193/lib/ruby/1.9.1/net/smtp.rb:519:in `start'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/mail-2.2.19/lib/mail/network/delivery_methods/smtp.rb:128:in `deliver!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/mail-2.2.19/lib/mail/message.rb:1989:in `do_delivery'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/mail-2.2.19/lib/mail/message.rb:230:in `block in deliver'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/actionmailer-3.0.20/lib/action_mailer/base.rb:426:in `block in deliver_mail'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/notifications.rb:52:in `block in instrument'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/notifications.rb:52:in `instrument'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/actionmailer-3.0.20/lib/action_mailer/base.rb:424:in `deliver_mail'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/mail-2.2.19/lib/mail/message.rb:230:in `deliver'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/devise-1.5.3/lib/devise/models/confirmable.rb:50:in `send_confirmation_instructions'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/callbacks.rb:456:in `_run_create_callbacks'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/callbacks.rb:277:in `create'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/persistence.rb:257:in `create_or_update'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/callbacks.rb:273:in `block in create_or_update'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/callbacks.rb:454:in `_run_save_callbacks'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/callbacks.rb:273:in `create_or_update'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/persistence.rb:60:in `save!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/validations.rb:49:in `save!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/transactions.rb:245:in `block in save!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/transactions.rb:292:in `block in with_transaction_returning_status'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/transactions.rb:207:in `transaction'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/method_tracer.rb:343:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/method_tracer.rb:341:in `transaction_with_trace_ActiveRecord_self_name_transaction'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/transactions.rb:290:in `with_transaction_returning_status'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/transactions.rb:245:in `save!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/validations.rb:34:in `create!'
C:/GitHub/Morphe/TaskTrakr/db/seeds.rb:23:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `block in load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `block in load_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:597:in `new_constants_in'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activerecord-3.0.20/lib/active_record/railties/databases.rake:290:in `block (2 levels) in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
C:/Ruby193/bin/rake:23:in `load'
C:/Ruby193/bin/rake:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:seed

Process finished with exit code 1
```

**Comment by bcardi** [comment]
**Resolution**
My understanding of the `enable_starttls_auto` option and SSL was incorrect. When `enable_starttls_auto` equals true, the SMTP port must support STARTTLS. For my SMTP provider (mailgun), this port should be **587** and not 465.
